name: conan-package

on:
  workflow_dispatch:
    inputs:
      conan_id:
        required: false
        type: string
        description: 'The full conan package ID, e.g. "curaengine_plugin_gradual_flow/1.2.3@ultimaker/stable"'
      create_latest_alias:
        required: true
        default: false
        type: boolean
        description: 'Create latest alias'

  push:
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'CuraEngineGradualFlow/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - '.github/workflows/conan-package.yml'
      - '.github/workflows/requirements-conan-package.txt'
    branches:
      - main
      - 'CURA-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]*'
      - '[0-9]+.[0-9]+.[0-9]'

jobs:
  conan-recipe-version:
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-version.yml@main
    with:
      project_name: curaengine_plugin_gradual_flow

  conan-package-export:
    needs: [ conan-recipe-version ]
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-export.yml@main
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
      recipe_id_latest: ${{ needs.conan-recipe-version.outputs.recipe_id_latest }}
    secrets: inherit
