name: conan-package

on:
  workflow_dispatch:
    inputs:
      conan_id:
        required: false
        type: string
        description: 'The full conan package ID, e.g. "curaengine_plugin_gradual_flow/1.2.3@ultimaker/stable"'
      create_latest_alias:
        required: true
        default: false
        type: boolean
        description: 'Create latest alias'

  push:
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'CuraEngineGradualFlow/**'
      - 'conanfile.py'
      - 'CMakeLists.txt'
      - '.github/workflows/conan-package.yml'
      - '.github/workflows/requirements-conan-package.txt'
    branches:
      - main
      - 'CURA-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]*'
      - '[0-9]+.[0-9]+.[0-9]'

jobs:
  # FIXME: Use `main` instead of `CURA-10831` once merged
  conan-recipe-version:
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-version.yml@CURA-10831
    with:
      project_name: curaengine_plugin_gradual_flow

  # FIXME: Use `main` instead of `CURA-10831` once merged
  conan-package-export:
    needs: [ conan-recipe-version ]
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-export.yml@CURA-10831
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
      recipe_id_latest: ${{ needs.conan-recipe-version.outputs.recipe_id_latest }}
    secrets: inherit

  # FIXME: Use `main` instead of `CURA-10831` once merged
  conan-package-create-macos:
    needs: [ conan-recipe-version, conan-package-export ]
    if: ${{ (github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'master' || needs.conan-recipe-version.outputs.is_release_branch == 'true')) }}
    uses: ultimaker/cura-workflows/.github/workflows/conan-package-create-macos.yml@CURA-10831
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
    secrets: inherit

  # FIXME: Use `main` instead of `CURA-10831` once merged
  conan-package-create-windows:
    needs: [ conan-recipe-version, conan-package-export ]
    if: ${{ (github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'master' || needs.conan-recipe-version.outputs.is_release_branch == 'true')) }}
    uses: ultimaker/cura-workflows/.github/workflows/conan-package-create-windows.yml@CURA-10831
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
    secrets: inherit

  # FIXME: Use `main` instead of `CURA-10831` once merged
  conan-package-create-linux:
    needs: [ conan-recipe-version, conan-package-export ]
    if: ${{ (github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'master' || needs.conan-recipe-version.outputs.is_release_branch == 'true')) }}
    uses: ultimaker/cura-workflows/.github/workflows/conan-package-create-linux.yml@CURA-10831
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
    secrets: inherit
