name: Create CuraPackage
run-name: ${{ inputs.plugin_conan_version }} by @${{ github.actor }}

on:
    workflow_dispatch:
        inputs:
            plugin_conan_version:
                description: 'Plugin Conan Version'
                default: '<plugin_conan_package>/latest@ultimaker/testing'
                required: true
                type: string
            conan_args:
                description: 'Conan args: eq.: --require-override'
                default: ''
                required: false
                type: string

jobs:
    windows-installer:
        uses: ./.github/workflows/windows.yml
        with:
            plugin_conan_version: ${{ inputs.plugin_conan_version }}
            conan_args: ${{ inputs.conan_args }}
            architecture: X64
            operating_system: windows-2022
        secrets: inherit

    linux-modern-installer:
        uses: ./.github/workflows/linux.yml
        with:
            plugin_conan_version: ${{ inputs.plugin_conan_version }}
            conan_args: ${{ inputs.conan_args }}
            architecture: X64
            operating_system: ubuntu-22.04
        secrets: inherit

    linux-legacy-installer:
        uses: ./.github/workflows/linux.yml
        with:
            plugin_conan_version: ${{ inputs.plugin_conan_version }}
            conan_args: ${{ inputs.conan_args }}
            architecture: X64
            operating_system: ubuntu-20.04
        secrets: inherit

    macos-installer:
        uses: ./.github/workflows/macos.yml
        with:
            plugin_conan_version: ${{ inputs.plugin_conan_version }}
            conan_args: ${{ inputs.conan_args }}
            architecture: X64
            operating_system: macos-11.0
        secrets: inherit

    macos-arm-installer:
        uses: ./.github/workflows/macos.yml
        with:
            plugin_conan_version: ${{ inputs.plugin_conan_version }}
            conan_args: ${{ inputs.conan_args }}
            architecture: ARM64
            operating_system: self-hosted
        secrets: inherit

    create-curapackages:
        runs-on: "ubuntu-latest"
        needs: [ windows-installer, linux-modern-installer, linux-legacy-installer, macos-installer, macos-arm-installer ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v3