name: unit-test
on:
  push:
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - '.github/workflows/unit-test.yml'
      - '.github/workflows/unit-test-post.yml'
    branches:
      - main
      - '[0-9]+.[0-9]+'

  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - '.github/workflows/unit-test.yml'
      - '.github/workflows/unit-test-post.yml'
    branches:
      - main
      - 'CURA-*'
      - '[0-9]+.[0-9]+'

permissions:
  contents: read

env:
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_USER }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASS }}

jobs:
  # FIXME: Change to `main` instead of `CURA-10831` once merged
  conan-recipe-version:
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-version.yml@CURA-10831
    with:
      project_name: curaengine_plugin_gradual_flow

  testing:
    uses: ultimaker/cura-workflows/.github/workflows/unit-test.yml@CURA-10831
    needs: [ conan-recipe-version ]
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
      conan_extra_args: '-c tools.build:skip_test=False'
      unit_test_cmd: 'ctest --output-junit plugin_test.xml'
      unit_test_dir: 'build/Release'
      build: true
